### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by BoisterousGaming** [paramsen/noise#3]
Hi, How do I get an Authentication to clone the git repo into my desktop?
Because i'm getting this error "Authentication failed. You may not have permission to access the repository or the repository may have been archived."

**Comment by paramsen** [comment]
Just cloning with the URL from the "Clone or download" button? Try using the https link instead `git clone https://github.com/paramsen/noise.git`.

**Comment by paramsen** [comment]
Tested to clone on another computer (not mine); Worked w/o any errors. There has to be something weird going on with your setup, might be a firewall/vpn/something stopping you - You can always choose to download as a zip in the "Clone and download" menu

**Comment by BoisterousGaming** [comment]
Ok, I have downloaded this project and kissfft directly as a zip file and it's working properly. Thanks for this great demo on how to use kissfft on android and your assistance.

**Comment by paramsen** [comment]
No problem, I'm happy to help!
